name: JAVIDSUB Auto Update

on:
  schedule:
    # اجرا هر ۶ ساعت یک‌بار (در دقایق 00 ساعت‌های 00:00, 06:00, 12:00, 18:00 به وقت UTC)
    - cron: "0 */6 * * *"
  workflow_dispatch: # امکان اجرای دستی از تب Actions

jobs:
  update-sub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Sing-box Core
        run: |
          SINGBOX_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          VERSION_NUM=${SINGBOX_VERSION#v}
          curl -LO "https://github.com/SagerNet/sing-box/releases/download/${SINGBOX_VERSION}/sing-box-${VERSION_NUM}-linux-amd64.tar.gz"
          tar -xzf "sing-box-${VERSION_NUM}-linux-amd64.tar.gz"
          mv "sing-box-${VERSION_NUM}-linux-amd64/sing-box" ./sing-box
          chmod +x ./sing-box

      - name: Install Dependencies
        run: pip install requests

      - name: Run Merge & Health Check Script
        env:
          MY_SUBS_LIST: ${{ secrets.MY_SUBS_LIST }}
        run: python process.py

      - name: Push Results
        run: |
          git config --global user.name "JAVID-BOT"
          git config --global user.email "bot@javid.com"
          git add JAVIDSUB.txt JAVIDSUB_B64.txt
          git commit -m "Auto Update (6-Hour Check): $(date)" || exit 0
          git push
